import { readdir, readFile, writeFile, copyFile, stat } from 'node:fs/promises';
import { join, extname } from 'node:path';

/**
 * Give the generated metadata images a .png extension.
 *
 * Next names route-generated images after their route, so a static export
 * writes `out/opengraph-image` with no extension. GitHub Pages picks the
 * Content-Type from the extension, so an extensionless file is served as
 * application/octet-stream and social scrapers reject it — the card
 * silently falls back to no image.
 *
 * This copies each one to a `.png` sibling and repoints the emitted markup
 * at it. The URLs being rewritten are machine-generated by Next, so the
 * pattern is exact rather than a guess at arbitrary HTML.
 */
const OUT = new URL('../out/', import.meta.url).pathname;
const PNG_MAGIC = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);

async function walk(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) files.push(...(await walk(full)));
    else files.push(full);
  }
  return files;
}

async function isPng(path) {
  if (extname(path)) return false;
  const { size } = await stat(path);
  if (size < 8) return false;
  const handle = await readFile(path);
  return handle.subarray(0, 8).equals(PNG_MAGIC);
}

const files = await walk(OUT);

const images = [];
for (const file of files) {
  if (await isPng(file)) {
    await copyFile(file, `${file}.png`);
    images.push(file.slice(OUT.length - 1));
  }
}

// Repoint markup and metadata at the .png copies, dropping Next's cache-
// busting query string along with the extensionless path.
//
// The RSC flight payload embedded in each page carries the same URLs with
// escaped quotes around them, so the trailing guard has to be "not a URL
// character" rather than a list of delimiters — otherwise the payload keeps
// the old path and client-side navigation disagrees with the served HTML.
//
// Longest path first, so /legal/x/opengraph-image is handled before the
// root /opengraph-image that is a suffix of it.
const rewritable = files.filter((f) => /\.(html|txt|xml|json)$/.test(f));
const ordered = [...images].sort((a, b) => b.length - a.length);
let touched = 0;
for (const file of rewritable) {
  const before = await readFile(file, 'utf8');
  let after = before;
  for (const image of ordered) {
    after = after.replaceAll(
      // `(?![\w.-])` also stops an already-rewritten `.png` matching again.
      new RegExp(`${image.replace(/[.*+?^${}()|[\]\\/-]/g, '\\$&')}(\\?[a-z0-9]+)?(?![\\w.-])`, 'g'),
      `${image}.png`,
    );
  }
  if (after !== before) {
    await writeFile(file, after);
    touched += 1;
  }
}

console.log(`fix-og-mime: ${images.length} images copied to .png, ${touched} files repointed`);
